import { useRef } from "react";
import { motion, useScroll, useTransform, useSpring } from "framer-motion";

export default function Intelligence() {
  const section1Ref = useRef(null);
  const section2Ref = useRef(null);
  const section3Ref = useRef(null);

  const { scrollYProgress: progress1Raw } = useScroll({
    target: section1Ref,
    offset: ["start end", "center center"],
  });
  const progress1 = useSpring(progress1Raw, {
    stiffness: 300,
    damping: 60,
    mass: 0.5,
  });

  const { scrollYProgress: progress2Raw } = useScroll({
    target: section2Ref,
    offset: ["start end", "center center"],
  });
  const progress2 = useSpring(progress2Raw, {
    stiffness: 300,
    damping: 60,
    mass: 0.5,
  });

  const { scrollYProgress: progress3Raw } = useScroll({
    target: section3Ref,
    offset: ["start end", "center center"],
  });
  const progress3 = useSpring(progress3Raw, {
    stiffness: 300,
    damping: 60,
    mass: 0.5,
  });

  const mobile1X = useTransform(progress1, [0, 1], [180, 0]);
  const mobile1Y = useTransform(progress1, [0, 1], [300, 0]);
  const mobile1Opacity = useTransform(progress1, [0, 0.4, 1], [0, 0.5, 1]);

  const mobile2Y = useTransform(progress2, [0, 1], [180, 0]);
  const mobile2X = useTransform(progress2, [0, 1], [80, 0]);
  const mobile2Opacity = useTransform(progress2, [0, 0.4, 1], [0, 0.5, 1]);

  const mobile3Y = useTransform(progress3, [0, 1], [300, 0]);
  const mobile3X = useTransform(progress3, [0, 1], [150, 0]);
  const mobile3Opacity = useTransform(progress3, [0, 0.4, 1], [0, 0.5, 1]);

  return (
    <div className="bg-black overflow-x-clip w-full">
     <div className="bg-black overflow-x-clip w-full">
      <div ref={section1Ref} className="relative py-60 md:py-5 overflow-x-clip">
        <div className="max-w-7xl mx-auto px-6 lg:px-8"> 
          <div className="flex flex-col lg:flex-row items-center gap-12">
            <div className="relative w-full lg:w-1/2 flex justify-start items-center h-125">
              <div className="absolute -inset-40 rounded-full blur-[120px] opacity-40 bg-purple-500/40 pointer-events-none" />
              <img
                src="https://acuitytrading.com/hubfs/DmR0FCkvXv-copy.jpg"
                alt="Trade Intelligence Tablet"
                className="w-full  lg:w-150 rounded-2xl z-10" 
              />
              <motion.img
                src="https://acuitytrading.com/hs-fs/hubfs/Mobile%20-%20AnalysisIQ%208.png?width=2163&height=1338&name=Mobile%20-%20AnalysisIQ%208.png"
                alt="Trade Intelligence Mobile"
                className="absolute w-90 lg:w-160 rounded-2xl z-20 left-[-20%]"
                style={{ y: mobile1Y, x: mobile1X, opacity: mobile1Opacity }}
              />
            </div>


            <div className="w-full lg:w-1/2 flex flex-col justify-center px-6 lg:px-12">
              <h2 className="text-4xl md:text-5xl font-semibold text-white mb-8">
                Trade Intelligence
              </h2>
              <p className="text-gray-300 text-base md:text-lg text-left sm:text-center lg:text-left  mb-4 leading-relaxed">
                Trade Intelligence delivers a steady stream of trade ideas with
                clear reasoning, generated by an AI-supported engine alongside
                expert analyst insight.
              </p>
              <p className="text-gray-300 text-base md:text-lg mb-8 leading-relaxed">
                AI adds context around sentiment and news impact. Experts
                provide the market judgment and the idea structure.
              </p>

              <button
                data-aos="zoom-in-up"
                data-aos-delay="300"
                data-aos-duration="700"
                className="group inline-flex items-center justify-between gap-4 px-6 py-4 rounded-full border border-purple-500 bg-transparent text-white font-medium transition-all hover:scale-105 w-fit shadow-[0_0_20px_rgba(139,92,246,0.25)]"
              >
                <span>Explore Trade Intelligence</span>
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-purple-300 transition-transform group-hover:translate-x-1">
                  →
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
</div>


      <div ref={section2Ref} className="relative py-60 md:py-5 overflow-x-clip">
  <div className="max-w-7xl mx-auto px-6 lg:px-8"> 
    <div className="flex flex-col lg:flex-row-reverse items-center gap-12">
      <div className="relative w-full lg:w-1/2 flex justify-end items-center h-125">
        <div className="absolute -inset-40 rounded-full blur-[120px] opacity-40 bg-blue-500/40 pointer-events-none" />
        <img
          src="https://acuitytrading.com/hubfs/DmR0FCkvXv-copy.jpg"
          alt="Market Intelligence Tablet"
          className="relative w-full  lg:w-150 lg:mr-10 rounded-2xl z-10"
        />
        <motion.img
          src="https://acuitytrading.com/hs-fs/hubfs/Tablet%20News%202.png?width=2265&height=1338&name=Tablet%20News%202.png"
          alt="Market Intelligence Mobile"
          className="absolute w-90 md:w-140 lg:w-140 rounded-2xl z-10 right-[-20%] lg:mr-0"
          style={{ y: mobile2Y, x: mobile2X, opacity: mobile2Opacity }}
        />
      </div>

      <div className="w-full lg:w-1/2 flex flex-col justify-center px-6 lg:px-12">
        <h2 className="text-4xl md:text-5xl font-semibold text-white mb-8">
          Market Intelligence
        </h2>
        <p className="text-gray-300 text-base md:text-lg mb-4 leading-relaxed">
          Market Intelligence uses AI to analyse real-time market
          developments and sentiment to explain why prices are moving.
        </p>
        <p className="text-gray-300 text-base md:text-lg mb-8 leading-relaxed">
          This sits where your traders trade, so you do not lose them to
          Twitter, Telegram, or random news feeds.
        </p>
        <button
          data-aos="zoom-in-up"
          data-aos-delay="300"
          data-aos-duration="700"
          className="group inline-flex items-center justify-between gap-4 px-6 py-4 rounded-full border border-blue-500 bg-transparent text-white font-medium transition-all hover:scale-105 w-fit shadow-[0_0_20px_rgba(59,130,246,0.25)]"
        >
          <span>Explore Market Intelligence</span>
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-500 transition-transform group-hover:translate-x-1">
            →
          </span>
        </button>
      </div>
    </div>
  </div>
</div>


     <div ref={section3Ref} className="relative py-60 md:py-5 overflow-x-clip">
  <div className="max-w-7xl mx-auto px-6 lg:px-8">
    <div className="flex flex-col lg:flex-row items-center gap-12">
      <div className="relative w-full lg:w-1/2 flex justify-start items-center h-125">
        <div className="absolute -inset-40 rounded-full blur-[120px] opacity-40 bg-pink-500/40 pointer-events-none" />
        <img
          src="https://acuitytrading.com/hubfs/DmR0FCkvXv-copy.jpg"
          alt="Event Intelligence Tablet"
          className="relative w-full lg:w-150 rounded-2xl z-10"
        />
        <motion.img
          src="https://acuitytrading.com/hs-fs/hubfs/Tablet%20Corp%20Calendar1.png?width=2055&height=1338&name=Tablet%20Corp%20Calendar1.png"
          alt="Event Intelligence Mobile"
          className="absolute w-90 lg:w-140 rounded-2xl z-20 left-[-20%]"
          style={{ y: mobile3Y, x: mobile3X, opacity: mobile3Opacity }}
        />
      </div>

      <div className="w-full lg:w-1/2 flex flex-col justify-center px-6 lg:px-12">
        <h2 className="text-4xl md:text-5xl font-semibold text-white mb-8">
          Event Intelligence
        </h2>
        <p className="text-gray-300 text-base md:text-lg mb-4 leading-relaxed">
          Your traders know market events matter; they just don't know how
          to act on them.
        </p>
        <p className="text-gray-300 text-base md:text-lg mb-8 leading-relaxed">
          Event Intelligence covers the economic and corporate events that
          drive volatility including major announcements, central bank
          decisions, and earnings.
        </p>
        <button
          data-aos="zoom-in-up"
          data-aos-delay="300"
          data-aos-duration="700"
          className="group inline-flex items-center justify-between gap-4 px-6 py-4 rounded-full border border-pink-500 bg-transparent text-white font-medium transition-all hover:scale-105 w-fit shadow-[0_0_20px_rgba(236,72,153,0.25)]"
        >
          <span>Explore Event Intelligence</span>
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-pink-500 transition-transform group-hover:translate-x-1">
            →
          </span>
        </button>
      </div>
    </div>
  </div>
</div>

    </div>
  );
}